export const courses = [
  {
    id: 'hsk12',
    level: 'A1–A2',
    hsk: 'HSK 1–2',
    title: 'HSK 1–2 эхлэл',
    subtitle: 'Авиа, үндсэн үг, өдөр тутмын яриа',
    duration: '8 долоо хоног',
    mode: 'Танхим + Online',
    schedule: 'Даваа · Лхагва 18:30–20:00',
    price: 289000,
    priceLabel: '₮289,000',
    seats: 16,
    points: ['Үндсэн авиа, бичих', 'Өдөр тутмын яриа', 'Шалгалтын загвар'],
    badge: 'Хамгийн эрэлттэй',
    description:
      'Хятад хэлтэй анх танилцаж буй суралцагчдад зориулсан бүрэн эхлэлийн хөтөлбөр. Жижиг бүлэгт авиа, иероглиф, ярианы суурийг зэрэгцүүлэн сурна.',
  },
  {
    id: 'hsk34',
    level: 'B1',
    hsk: 'HSK 3–4',
    title: 'HSK 3–4 бэлтгэл',
    subtitle: 'Дүрэм, listening, mock test',
    duration: '10 долоо хоног',
    mode: 'Танхим',
    schedule: 'Мягмар · Пүрэв 18:30–20:30',
    price: 389000,
    priceLabel: '₮389,000',
    seats: 14,
    points: ['Дүрэм гүнзгийрүүлэх', 'Listening drill', 'Mock test'],
    badge: null,
    description:
      'HSK 3–4 түвшинд бэлдэх эрчимтэй анги. Шалгалтын формат, цаг хэмнэх стратеги, listening дасгалыг системтэйгээр хийнэ.',
  },
  {
    id: 'speak',
    level: 'Яриа',
    hsk: 'Spoken',
    title: 'Spoken Chinese Lab',
    subtitle: 'Жинхэнэ яриа, role-play, дуудлага',
    duration: '6 долоо хоног',
    mode: 'Жижиг бүлэг',
    schedule: 'Баасан 19:00–20:30',
    price: 259000,
    priceLabel: '₮259,000',
    seats: 10,
    points: ['Native coach', 'Role-play', 'Pronunciation check'],
    badge: 'Gen Z pick',
    description:
      'Зөвхөн ярианд төвлөрсөн lab. Кафе, их сургууль, аялал, ажил — бодит нөхцөлд ашиглах хэллэгүүдийг дадлагажуулна.',
  },
  {
    id: 'biz',
    level: 'Business',
    hsk: 'Business',
    title: 'Business Mandarin',
    subtitle: 'Meeting, WeChat, negotiation',
    duration: '8 долоо хоног',
    mode: 'Оройн анги',
    schedule: 'Даваа · Пүрэв 20:00–21:30',
    price: 420000,
    priceLabel: '₮420,000',
    seats: 12,
    points: ['Meeting Chinese', 'Email & WeChat', 'Negotiation phrases'],
    badge: null,
    description:
      'Бизнес орчинд хэрэгтэй хятад хэл. Уулзалт, захидал, WeChat харилцаа, хэлэлцээрийн үндсэн хэллэгийг сурна.',
  },
  {
    id: 'kids',
    level: 'Kids',
    hsk: 'Kids',
    title: 'Хүүхдийн Хятад хэл',
    subtitle: 'Тоглоом, дуу, зураг — хөгжилтэй сургалт',
    duration: '12 долоо хоног',
    mode: 'Амралтын өдөр',
    schedule: 'Бямба 11:00–12:30',
    price: 220000,
    priceLabel: '₮220,000',
    seats: 12,
    points: ['Тоглоомын арга', 'Дуу, зураг', 'Эцэг эхийн тайлан'],
    badge: null,
    description:
      '7–12 насны хүүхдэд зориулсан хөгжилтэй хөтөлбөр. Дуу, тоглоом, зургаар хэлний сонирхлыг төлөвшүүлнэ.',
  },
  {
    id: 'intensive',
    level: 'Intensive',
    hsk: 'Prep',
    title: 'Хятад руу явахаас өмнө',
    subtitle: 'Campus survival + зуучлалтай бэлтгэл',
    duration: '4 долоо хоног',
    mode: 'Эрчимжүүлсэн',
    schedule: 'Да–Ба 17:30–19:30',
    price: 490000,
    priceLabel: '₮490,000',
    seats: 8,
    points: ['Campus survival', 'Visa interview', 'Daily immersion'],
    badge: 'Зуучлалтай',
    description:
      'Хятад руу явахаас өмнөх 4 долоо хоногийн эрчимжүүлсэн бэлтгэл. Кампус амьдрал, ярилцлага, өдөр тутмын хэл.',
  },
]
