export const courses = [
  {
    id: 'french-a1',
    type: 'language',
    level: 'A1',
    hsk: 'FR A1',
    title: 'Франц хэлний анхан шат',
    subtitle: 'France Au Pair 2027-д бэлтгэх анги',
    duration: '3 сар',
    mode: 'Танхим',
    schedule: '2026.10.18-нд эхэлнэ',
    price: 0,
    priceLabel: 'Зөвлөгөө аваарай',
    seats: 12,
    points: ['Анхан шатны яриа', 'Гэр бүлийн өдөр тутмын хэл', 'Соёл, дүрэм'],
    badge: 'Элсэлт нээлттэй',
    description:
      'Франц руу Au Pair-аар явах залууст зориулсан анхан шатны франц хэлний анги. 10-р сарын 18-нд эхэлнэ.',
  },
  {
    id: 'german-a1',
    type: 'language',
    level: 'A1',
    hsk: 'DE A1',
    title: 'Герман хэлний анхан шат',
    subtitle: 'Герман, Австри, Швейцарьт бэлтгэх',
    duration: '3 сар',
    mode: 'Танхим',
    schedule: 'Өдөр / Орой',
    price: 0,
    priceLabel: 'Зөвлөгөө аваарай',
    seats: 14,
    points: ['A1 яриа, сонсох', 'Хүүхэд харах үгийн сан', 'Визийн ярилцлага'],
    badge: 'Элсэлт нээлттэй',
    description:
      'Герман хэлтэй орнуудад Au Pair хийх суурь бэлтгэл. Өдөр тутмын яриа, гэр бүлийн орчин, энгийн дүрэм.',
  },
  {
    id: 'german-a2',
    type: 'language',
    level: 'A2',
    hsk: 'DE A2',
    title: 'Герман хэл A2',
    subtitle: 'Гэр бүл, сургууль, өдөр тутмын харилцаа',
    duration: '3 сар',
    mode: 'Танхим',
    schedule: 'Оройн анги',
    price: 0,
    priceLabel: 'Зөвлөгөө аваарай',
    seats: 12,
    points: ['A2 түвшин', 'Хүүхэдтэй харилцах', 'Бичиг баримтын хэл'],
    badge: null,
    description: 'Герман Au Pair-т шаардлагатай A2 түвшинд бэлтгэнэ.',
  },
  {
    id: 'eiffel',
    type: 'language',
    level: 'Франц',
    hsk: 'Eiffel',
    title: 'AuPair Eiffel — Франц',
    subtitle: 'Alliance Française-тай хамтарсан хөтөлбөр',
    duration: '12 сар',
    mode: 'Соёл солилцоо',
    schedule: '2027 оны элсэлт',
    price: 0,
    priceLabel: 'Зөвлөгөө аваарай',
    seats: 10,
    points: ['Францад 1 жил', 'Хэлний сургалт', 'Гэр бүлд амьдрах'],
    badge: '50% дүүрсэн',
    reserved: 5,
    description:
      'Mongolian AuPair болон Alliance Française d’Oulan-Bator-ийн хамтарсан AuPair Eiffel хөтөлбөр. Францад нэг жил соёл солилцоо.',
  },
  {
    id: 'germany',
    type: 'country',
    level: 'Au Pair',
    hsk: 'DE',
    title: 'Герман Au Pair',
    subtitle: 'Гэр бүлд амьдарч, герман хэл сурна',
    duration: '6–12 сар',
    mode: 'Соёл солилцоо',
    schedule: 'Элсэлт нээлттэй',
    price: 0,
    priceLabel: 'Зөвлөгөө үнэгүй',
    seats: 12,
    points: ['Хэлний курс', 'Халаасны мөнгө', 'Виза, гэр бүл'],
    badge: 'Эрэлттэй',
    description:
      'Герман дахь албан ёсны Au Pair хөтөлбөр. Гэр бүлд амьдарч, хүүхэд харан, герман хэл, соёлыг сурна.',
  },
  {
    id: 'france',
    type: 'country',
    level: 'Au Pair',
    hsk: 'FR',
    title: 'Франц Au Pair 2027',
    subtitle: '10 суудал · 50% дүүрсэн',
    duration: '12 сар',
    mode: 'Соёл солилцоо',
    schedule: 'Элсэлт нээлттэй',
    price: 0,
    priceLabel: 'Зөвлөгөө үнэгүй',
    seats: 10,
    points: ['10 суудал', 'AuPair Eiffel', 'Франц хэлний анги'],
    badge: 'Элсэлт нээлттэй',
    reserved: 5,
    description:
      'France Au Pair 2027 — 10 суудал, одоогоор 50% дүүрсэн. Франц хэлний анхан шат 10-р сарын 18-нд эхэлнэ.',
  },
  {
    id: 'austria',
    type: 'country',
    level: 'Au Pair',
    hsk: 'AT',
    title: 'Австри Au Pair',
    subtitle: 'Вена болон бусад хотууд',
    duration: '6–12 сар',
    mode: 'Соёл солилцоо',
    schedule: 'Элсэлт нээлттэй',
    price: 0,
    priceLabel: 'Зөвлөгөө үнэгүй',
    seats: 8,
    points: ['Герман хэл', 'Аюулгүй орчин', 'Гэр бүл'],
    badge: null,
    description: 'Австрийн гэр бүлд Au Pair-аар амьдарч, герман хэл сурна.',
  },
  {
    id: 'switzerland',
    type: 'country',
    level: 'Au Pair',
    hsk: 'CH',
    title: 'Швейцарь Au Pair',
    subtitle: 'Герман / франц хэлтэй гэр бүл',
    duration: '6–12 сар',
    mode: 'Соёл солилцоо',
    schedule: 'Элсэлт нээлттэй',
    price: 0,
    priceLabel: 'Зөвлөгөө үнэгүй',
    seats: 6,
    points: ['Олон хэл', 'Өндөр амьжиргаа', 'Уул, хот'],
    badge: null,
    description: 'Швейцарьт герман эсвэл франц хэлтэй гэр бүлд Au Pair хийнэ.',
  },
  {
    id: 'belgium',
    type: 'country',
    level: 'Au Pair',
    hsk: 'BE',
    title: 'Бельги Au Pair',
    subtitle: 'Европын төв · Брюссель',
    duration: '6–12 сар',
    mode: 'Соёл солилцоо',
    schedule: 'Элсэлт нээлттэй',
    price: 0,
    priceLabel: 'Зөвлөгөө үнэгүй',
    seats: 6,
    points: ['Франц / нидерланд', 'Брюссель', 'Олон улсын орчин'],
    badge: null,
    description: 'Бельгид франц эсвэл нидерланд хэлтэй гэр бүлд Au Pair хийнэ.',
  },
  {
    id: 'netherlands',
    type: 'country',
    level: 'Au Pair',
    hsk: 'NL',
    title: 'Нидерланд Au Pair',
    subtitle: 'Амстердам · нээлттэй соёл',
    duration: '6–12 сар',
    mode: 'Соёл солилцоо',
    schedule: 'Элсэлт нээлттэй',
    price: 0,
    priceLabel: 'Зөвлөгөө үнэгүй',
    seats: 6,
    points: ['Англи хэлтэй орчин', 'Аюулгүй нийгэм', 'Хэлний курс'],
    badge: null,
    description: 'Нидерландад Au Pair-аар амьдарч, англи/нидерланд хэлтэй орчинд суралцана.',
  },
  {
    id: 'denmark',
    type: 'country',
    level: 'Au Pair',
    hsk: 'DK',
    title: 'Дани Au Pair',
    subtitle: 'Копенгаген · Скандинав',
    duration: '6–12 сар',
    mode: 'Соёл солилцоо',
    schedule: 'Элсэлт нээлттэй',
    price: 0,
    priceLabel: 'Зөвлөгөө үнэгүй',
    seats: 5,
    points: ['Скандинав амьдрал', 'Англи хэл', 'Аюулгүй орчин'],
    badge: 'Скандинав',
    description: 'Дани улсад Au Pair хийж, Скандинавын гэр бүлтэй танилцана.',
  },
]
