export const navLinks = [
  { to: '/', label: 'Нүүр' },
  { to: '/courses', label: 'Хөтөлбөр' },
  { to: '/universities', label: 'Улс орнууд' },
  { to: '/shop', label: 'Дэлгүүр' },
  { to: '/profile', label: 'Холбоо' },
]

export const social = {
  facebook: 'https://www.facebook.com/MongolianAuPair',
  messenger: 'https://m.me/MongolianAuPair',
  instagram: 'https://www.instagram.com/mongolian.aupair',
  website: 'https://mongolianaupair.com/',
  email: 'office@mongolianaupair.com',
  emailAlt: 'info@mongolianaupair.com',
  phone: '+976 7711-6906',
  phoneAlt: '+976 7711-6906',
  phoneTel: '+97677116906',
  phoneAltTel: '+97677116906',
  address:
    'Улаанбаатар хот, Сүхбаатар дүүрэг, 11-р хороо, 7-р хороолол, Нью Резиденс хотхон, 726-р байр, 1 тоот',
  city: 'Улаанбаатар',
  map: 'https://maps.google.com/maps?q=New+Residence+Sukhbaatar+Ulaanbaatar',
  followers: 'Албан ёсны',
  recommend: '1969 оны конвенц',
  hours: 'Нээлттэй',
  since: '2005',
  placed: '3,000+',
}

export const feed = {
  featured: {
    tag: 'Элсэлт авч байна',
    title: 'France Au Pair 2027 — 10 суудал, 50% дүүрсэн',
    meta: 'Франц хэлний анхан шат · 10/18-нд эхэлнэ',
    to: '/universities/france',
    image:
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1400&q=80',
    source: 'Facebook · Mongolian AuPair',
  },
  side: [
    {
      tag: 'Франц',
      title: 'Франц хэлний анхан шат 10/18-нд эхэлнэ',
      to: '/courses/french-a1',
    },
    {
      tag: 'Герман',
      title: 'Герман Au Pair элсэлт нээлттэй',
      to: '/universities/germany',
    },
    {
      tag: 'Хаяг',
      title: 'New Residence 726-1 · Сүхбаатар',
      to: '/profile',
    },
  ],
}

export const stories = [
  {
    id: 1,
    category: 'Туршлага',
    title: `${social.since} оноос хойш соёл солилцоо`,
    time: '20 жил',
  },
  {
    id: 2,
    category: 'Залуус',
    title: `${social.placed} оролцогч Европын гэр бүлд`,
    time: 'Идэвхтэй',
  },
  {
    id: 3,
    category: 'Хөтөлбөр',
    title: '7 улс · элсэлт авч байна',
    time: social.hours,
  },
]

export const coursesFallback = [
  {
    id: 'french-a1',
    type: 'language',
    level: 'A1',
    hsk: 'FR A1',
    title: 'Франц хэлний анхан шат',
    subtitle: 'France Au Pair 2027-д бэлтгэх анги',
    duration: '3 сар',
    mode: 'Танхим',
    schedule: '2026.10.18-нд эхэлнэ',
    priceLabel: 'Зөвлөгөө аваарай',
    seats: 12,
    seatsLeft: 6,
    points: ['Анхан шатны яриа', 'Гэр бүлийн өдөр тутмын хэл', 'Соёл, дүрэм'],
    badge: 'Элсэлт нээлттэй',
    description:
      'Франц руу Au Pair-аар явах залууст зориулсан анхан шатны франц хэлний анги. 10-р сарын 18-нд эхэлнэ.',
  },
  {
    id: 'german-a1',
    type: 'language',
    level: 'A1',
    hsk: 'DE A1',
    title: 'Герман хэлний анхан шат',
    subtitle: 'Герман, Австри, Швейцарьт бэлтгэх',
    duration: '3 сар',
    mode: 'Танхим',
    schedule: 'Өдөр / Орой',
    priceLabel: 'Зөвлөгөө аваарай',
    seats: 14,
    seatsLeft: 8,
    points: ['A1 яриа, сонсох', 'Хүүхэд харах үгийн сан', 'Визийн ярилцлага'],
    badge: 'Элсэлт нээлттэй',
    description:
      'Герман хэлтэй орнуудад Au Pair хийх суурь бэлтгэл. Өдөр тутмын яриа, гэр бүлийн орчин, энгийн дүрэм.',
  },
  {
    id: 'german-a2',
    type: 'language',
    level: 'A2',
    hsk: 'DE A2',
    title: 'Герман хэл A2',
    subtitle: 'Гэр бүл, сургууль, өдөр тутмын харилцаа',
    duration: '3 сар',
    mode: 'Танхим',
    schedule: 'Оройн анги',
    priceLabel: 'Зөвлөгөө аваарай',
    seats: 12,
    seatsLeft: 7,
    points: ['A2 түвшин', 'Хүүхэдтэй харилцах', 'Бичиг баримтын хэл'],
    badge: null,
    description: 'Герман Au Pair-т шаардлагатай A2 түвшинд бэлтгэнэ.',
  },
  {
    id: 'eiffel',
    type: 'language',
    level: 'Франц',
    hsk: 'Eiffel',
    title: 'AuPair Eiffel — Франц',
    subtitle: 'Alliance Française-тай хамтарсан хөтөлбөр',
    duration: '12 сар',
    mode: 'Соёл солилцоо',
    schedule: '2027 оны элсэлт',
    priceLabel: 'Зөвлөгөө аваарай',
    seats: 10,
    seatsLeft: 5,
    points: ['Францад 1 жил', 'Хэлний сургалт', 'Гэр бүлд амьдрах'],
    badge: '50% дүүрсэн',
    description:
      'Mongolian AuPair болон Alliance Française d’Oulan-Bator-ийн хамтарсан AuPair Eiffel хөтөлбөр. Францад нэг жил соёл солилцоо.',
  },
]

export const courses = coursesFallback.map((c) => ({
  ...c,
  price: c.priceLabel,
}))

export const countries = [
  {
    id: 'germany',
    name: 'Germany',
    nameMn: 'Герман',
    short: 'DE',
    city: 'Берлин',
    region: 'Төв Европ',
    language: 'Герман хэл',
    langGroup: 'german',
    focus: 'Au Pair · хэл, соёл',
    intake: 'Элсэлт нээлттэй',
    hsk: 'A1–A2',
    duration: '6–12 сар',
    tuition: 'Хоол, байр + халаасны мөнгө',
    priceLabel: 'Зөвлөгөө үнэгүй',
    badge: 'Эрэлттэй',
    featured: true,
    open: true,
    seats: 12,
    seatsLeft: 8,
    image:
      'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1400&q=80',
    description:
      'Герман дахь албан ёсны Au Pair хөтөлбөр. Гэр бүлд амьдарч, хүүхэд харан, герман хэл, соёлыг өдөр тутмын орчинд сурна.',
    points: [
      'Европын хамгийн том Au Pair зах зээл',
      'Хэлний курс + халаасны мөнгө',
      'Виза, гэр бүлтэй тохирох процессыг бид хамт хийнэ',
    ],
    requirements: [
      '18–30 нас',
      'Паспорт',
      'Герман хэл A1-ээс',
      'Хүүхэд харах сонирхол, туршлага',
      'Эрүүл мэндийн үзлэг',
    ],
    why: 'Герман хэл сурч, Европын төвд соёл солилцоо хийхийг хүсвэл эхний сонголт.',
  },
  {
    id: 'france',
    name: 'France',
    nameMn: 'Франц',
    short: 'FR',
    city: 'Парис',
    region: 'Баруун Европ',
    language: 'Франц хэл',
    langGroup: 'french',
    focus: 'Au Pair Eiffel · 2027',
    intake: 'Элсэлт нээлттэй',
    hsk: 'A1+',
    duration: '12 сар',
    tuition: 'Хоол, байр + халаасны мөнгө',
    priceLabel: 'Зөвлөгөө үнэгүй',
    badge: 'Элсэлт нээлттэй',
    featured: true,
    open: true,
    seats: 10,
    seatsLeft: 5,
    image:
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1400&q=80',
    description:
      'France Au Pair 2027 — 10 суудал, одоогоор 50% дүүрсэн. Франц хэлний анхан шат 10-р сарын 18-нд эхэлнэ.',
    points: [
      '10 суудал · 50% дүүрсэн',
      'Alliance Française-тай хамтарсан Eiffel хөтөлбөр',
      'Франц хэлний бэлтгэл ангитай',
    ],
    requirements: [
      '18–30 нас',
      'Паспорт',
      'Франц хэлний анхан шат (суралцаж болно)',
      'Хүүхэд харах хүсэл',
      'Бүртгэлийн маягт',
    ],
    why: 'Францад нэг жил амьдарч, хэл сурч, соёл солилцоо хийх шинэ боломж — суудал хязгаартай.',
  },
  {
    id: 'austria',
    name: 'Austria',
    nameMn: 'Австри',
    short: 'AT',
    city: 'Вена',
    region: 'Төв Европ',
    language: 'Герман хэл',
    langGroup: 'german',
    focus: 'Au Pair · гэр бүл',
    intake: 'Элсэлт нээлттэй',
    hsk: 'A1–A2',
    duration: '6–12 сар',
    tuition: 'Хоол, байр + халаасны мөнгө',
    priceLabel: 'Зөвлөгөө үнэгүй',
    badge: null,
    featured: true,
    open: true,
    seats: 8,
    seatsLeft: 6,
    image:
      'https://images.unsplash.com/photo-1609856878074-cf31e21ccb6b?auto=format&fit=crop&w=1400&q=80',
    description:
      'Австрийн гэр бүлд Au Pair-аар амьдарч, герман хэл, Альпийн соёлтой танилцана.',
    points: [
      'Вена болон бусад хотууд',
      'Герман хэлний орчин',
      'Аюулгүй, тохилог гэр бүлүүд',
    ],
    requirements: [
      '18–30 нас',
      'Паспорт',
      'Герман хэл A1+',
      'Хүүхэд харах туршлага',
      'Эрүүл мэндийн үзлэг',
    ],
    why: 'Герман хэлтэй, аюулгүй орчинд Au Pair хийхийг хүсвэл Австри тохиромжтой.',
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    nameMn: 'Швейцарь',
    short: 'CH',
    city: 'Цюрих',
    region: 'Төв Европ',
    language: 'Герман / Франц',
    langGroup: 'german',
    focus: 'Au Pair · олон хэл',
    intake: 'Элсэлт нээлттэй',
    hsk: 'A2+',
    duration: '6–12 сар',
    tuition: 'Хоол, байр + халаасны мөнгө',
    priceLabel: 'Зөвлөгөө үнэгүй',
    badge: null,
    featured: true,
    open: true,
    seats: 6,
    seatsLeft: 4,
    image:
      'https://images.unsplash.com/photo-1527668752968-14dc70a27c10?auto=format&fit=crop&w=1400&q=80',
    description:
      'Швейцарьт герман эсвэл франц хэлтэй гэр бүлд Au Pair хийж, олон хэл, өндөр амьдралын орчинд суралцана.',
    points: ['Олон хэлний орчин', 'Өндөр амьжиргаа', 'Уулын болон хотын гэр бүл'],
    requirements: [
      '18–30 нас',
      'Паспорт',
      'Герман эсвэл франц A2+',
      'Хүүхэд харах туршлага',
      'Санхүүгийн баталгаа (зарим тохиолдолд)',
    ],
    why: 'Олон хэл, өндөр амьдралын орчинд соёл солилцоо хийхийг хүсвэл.',
  },
  {
    id: 'belgium',
    name: 'Belgium',
    nameMn: 'Бельги',
    short: 'BE',
    city: 'Брюссель',
    region: 'Баруун Европ',
    language: 'Франц / Нидерланд',
    langGroup: 'french',
    focus: 'Au Pair · Европын төв',
    intake: 'Элсэлт нээлттэй',
    hsk: 'A1+',
    duration: '6–12 сар',
    tuition: 'Хоол, байр + халаасны мөнгө',
    priceLabel: 'Зөвлөгөө үнэгүй',
    badge: null,
    featured: false,
    open: true,
    seats: 6,
    seatsLeft: 5,
    image:
      'https://images.unsplash.com/photo-1559113202-c916b8e44373?auto=format&fit=crop&w=1400&q=80',
    description:
      'Бельгид франц эсвэл нидерланд хэлтэй гэр бүлд Au Pair хийж, Европын зүрхэнд амьдарна.',
    points: ['Брюссель — Европын төв', 'Франц / нидерланд хэл', 'Олон улсын орчин'],
    requirements: [
      '18–30 нас',
      'Паспорт',
      'Франц эсвэл нидерланд хэлний суурь',
      'Хүүхэд харах хүсэл',
      'Эрүүл мэндийн үзлэг',
    ],
    why: 'Европын төвд, франц хэлтэй орчинд Au Pair хийхийг хүсвэл.',
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    nameMn: 'Нидерланд',
    short: 'NL',
    city: 'Амстердам',
    region: 'Баруун Европ',
    language: 'Нидерланд / Англи',
    langGroup: 'north',
    focus: 'Au Pair · нээлттэй соёл',
    intake: 'Элсэлт нээлттэй',
    hsk: 'A1+',
    duration: '6–12 сар',
    tuition: 'Хоол, байр + халаасны мөнгө',
    priceLabel: 'Зөвлөгөө үнэгүй',
    badge: null,
    featured: true,
    open: true,
    seats: 6,
    seatsLeft: 4,
    image:
      'https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?auto=format&fit=crop&w=1400&q=80',
    description:
      'Нидерландад Au Pair-аар амьдарч, дугуй, нээлттэй соёл, англи/нидерланд хэлтэй өдөр тутмын орчинд суралцана.',
    points: ['Англи хэлтэй орчин', 'Аюулгүй, нээлттэй нийгэм', 'Хэлний курс'],
    requirements: [
      '18–30 нас',
      'Паспорт',
      'Англи хэлний суурь',
      'Хүүхэд харах туршлага',
      'Эрүүл мэндийн үзлэг',
    ],
    why: 'Англи хэлтэй, нээлттэй орчинд Европын амьдралыг мэдрэхийг хүсвэл.',
  },
  {
    id: 'denmark',
    name: 'Denmark',
    nameMn: 'Дани',
    short: 'DK',
    city: 'Копенгаген',
    region: 'Хойд Европ',
    language: 'Дани / Англи',
    langGroup: 'north',
    focus: 'Au Pair · Скандинав',
    intake: 'Элсэлт нээлттэй',
    hsk: 'A1+',
    duration: '6–12 сар',
    tuition: 'Хоол, байр + халаасны мөнгө',
    priceLabel: 'Зөвлөгөө үнэгүй',
    badge: 'Скандинав',
    featured: false,
    open: true,
    seats: 5,
    seatsLeft: 3,
    image:
      'https://images.unsplash.com/photo-1513622470522-26c3e3b0c1a6?auto=format&fit=crop&w=1400&q=80',
    description:
      'Дани улсад Au Pair хийж, Скандинавын гэр бүл, англи хэлтэй орчин, өндөр амьдралын хэв маягтай танилцана.',
    points: ['Скандинав амьдрал', 'Англи хэлтэй гэр бүл', 'Аюулгүй орчин'],
    requirements: [
      '18–30 нас',
      'Паспорт',
      'Англи хэлний суурь',
      'Хүүхэд харах хүсэл',
      'Эрүүл мэндийн үзлэг',
    ],
    why: 'Хойд Европын аюулгүй, англи хэлтэй орчинд Au Pair хийхийг хүсвэл.',
  },
]

export const universities = countries

export const videos = [
  {
    id: 'r1',
    href: 'https://www.facebook.com/MongolianAuPair',
    title: 'France Au Pair 2027 элсэлт',
    category: 'Элсэлт',
    views: 'Шинэ',
    thumb:
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'r2',
    href: 'https://www.facebook.com/MongolianAuPair',
    title: 'Герман дахь Au Pair амьдрал',
    category: 'Герман',
    views: 'Reel',
    thumb:
      'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'r3',
    href: 'https://www.facebook.com/MongolianAuPair',
    title: 'Соёл солилцоогоор дэлхийд',
    category: 'Мэдээ',
    views: 'Page',
    thumb:
      'https://images.unsplash.com/photo-1527668752968-14dc70a27c10?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'r4',
    href: 'https://www.instagram.com/mongolian.aupair',
    title: 'Instagram · mongolian.aupair',
    category: 'Reel',
    views: 'IG',
    thumb:
      'https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?auto=format&fit=crop&w=800&q=80',
  },
]

export const products = [
  {
    id: 'p1',
    name: 'Герман хэлний анхан шатны ном',
    price: 'Зөвлөгөө',
    tag: 'Хэл',
    blurb: 'Au Pair бэлтгэл',
    description: 'Герман Au Pair-т зориулсан анхан шатны материал.',
    points: ['A1 үгс', 'Гэр бүлийн яриа', 'Практик'],
  },
  {
    id: 'p2',
    name: 'Франц хэлний анхан шатны ном',
    price: 'Зөвлөгөө',
    tag: 'Хэл',
    blurb: 'France 2027',
    description: 'Франц Au Pair-т зориулсан анхан шатны материал.',
    points: ['A1 үгс', 'Өдөр тутмын яриа', 'Соёл'],
  },
  {
    id: 'p3',
    name: 'Бичиг баримтын чеклист',
    price: 'Үнэгүй',
    tag: 'Виза',
    blurb: 'Элсэлтийн жагсаалт',
    description: 'Паспорт, анкет, эрүүл мэнд — Au Pair бүртгэлийн чеклист.',
    points: ['Виза', 'Гэр бүл', 'Хэлний үнэмлэх'],
  },
]
