export const navLinks = [
  { to: '/', label: 'Нүүр' },
  { to: '/courses', label: 'Сургалт' },
  { to: '/universities', label: 'Их сургууль' },
  { to: '/videos', label: 'Бичлэг' },
  { to: '/shop', label: 'Дэлгүүр' },
  { to: '/profile', label: 'Профайл' },
]

export const social = {
  facebook: 'https://www.facebook.com/HanzAcademy',
  messenger: 'https://m.me/HanzAcademy',
  email: 'info@bumtankhanz.mn',
  phone: '+976 9999-1573',
  phoneAlt: '+976 9990-7748',
  phoneTel: '+97699991573',
  phoneAltTel: '+97699907748',
  address: 'СБД 1-р хороо, Замын цагдаагийн зүүн талд, UNION BUILDING A блок, 12 давхар, 1204 тоот',
  city: 'Улаанбаатар',
  map: 'https://maps.google.com/maps?q=47.90774658,106.92610052',
  followers: '72K',
  recommend: '82%',
  hours: 'Нээлттэй',
}

export const feed = {
  featured: {
    tag: 'Элсэлт авч байна',
    title: 'HSK 1–5 бүх түвшний анги нээлттэй',
    meta: 'Эрчимжүүлсэн · Энгийн · Ганцаарчилсан',
    to: '/courses',
    image: '/cover.jpg',
    source: 'Facebook · 9 сарын 18',
  },
  side: [
    {
      tag: 'Хуваарь',
      title: 'Эрчимжүүлсэн 6 сарын / 1 сарын анги',
      to: '/courses',
    },
    {
      tag: 'Ганцаарчилсан',
      title: '7 хоногийн ганцаарчилсан хичээл',
      to: '/profile',
    },
    {
      tag: 'Хаяг',
      title: 'Union Building 1204 · СБД',
      to: '/profile',
    },
  ],
}

export const stories = [
  {
    id: 1,
    category: 'Community',
    title: `${social.followers} дагагч Facebook дээр`,
    time: 'Идэвхтэй',
  },
  {
    id: 2,
    category: 'Үнэлгээ',
    title: `${social.recommend} зөвлөдөг`,
    time: '11 review',
  },
  {
    id: 3,
    category: 'Байршил',
    title: 'Union Building · 1204',
    time: social.hours,
  },
]

export const coursesFallback = [
  {
    id: 'hsk12',
    level: 'Эхлэл',
    hsk: 'HSK 1–2',
    title: 'HSK 1–2 эхлэлийн анги',
    subtitle: 'Авиа, үндсэн үгс, өдөр тутмын яриа',
    duration: '1–6 сар',
    mode: 'Танхим',
    schedule: 'Өдөр / Орой',
    priceLabel: 'Зөвлөгөө аваарай',
    seatsLeft: 12,
    points: ['HSK 1–2 бүрэн хөтөлбөр', 'Туршлагатай багш', 'Тохилог орчин'],
    badge: 'Элсэлт нээлттэй',
    description:
      'Хятад хэлтэй анх танилцаж буй суралцагчдад зориулсан суурь хөтөлбөр. HSK 1–2 түвшинд бэлтгэнэ.',
  },
  {
    id: 'hsk34',
    level: 'Дунд',
    hsk: 'HSK 3–4',
    title: 'HSK 3–4 бэлтгэлийн анги',
    subtitle: 'Дүрэм, сонсох, ярианы чадвар',
    duration: '1–6 сар',
    mode: 'Танхим',
    schedule: 'Өдөр / Орой',
    priceLabel: 'Зөвлөгөө аваарай',
    seatsLeft: 10,
    points: ['Дүрэм гүнзгийрүүлэх', 'Listening дасгал', 'Шалгалтын бэлтгэл'],
    badge: null,
    description: 'HSK 3–4 түвшинд системтэй бэлтгэх хөтөлбөр.',
  },
  {
    id: 'hsk5',
    level: 'Ахисан',
    hsk: 'HSK 5',
    title: 'HSK 5 ахисан анги',
    subtitle: 'Гүнзгийрүүлсэн бэлтгэл',
    duration: 'Эрчимжүүлсэн',
    mode: 'Танхим',
    schedule: 'Урт цагийн хуваарь',
    priceLabel: 'Зөвлөгөө аваарай',
    seatsLeft: 8,
    points: ['HSK 5 бүрэн бэлтгэл', 'Бичих · Ярих', 'Mock шалгалт'],
    badge: 'Эрэлттэй',
    description: 'HSK 5 түвшинд гүнзгийрүүлэн бэлтгэх анги.',
  },
  {
    id: 'intensive6',
    level: 'Эрчимжүүлсэн',
    hsk: '6 сар',
    title: 'Эрчимжүүлсэн 6 сарын анги',
    subtitle: 'Өдрийн цаг · бүрэн хөтөлбөр',
    duration: '6 сар',
    mode: 'Эрчимжүүлсэн',
    schedule: 'Өдрийн цаг',
    priceLabel: 'Зөвлөгөө аваарай',
    seatsLeft: 10,
    points: ['Өдөр бүр хичээл', 'HSK 1–5 замнал', 'Багшийн хяналт'],
    badge: 'Элсэлт нээлттэй',
    description:
      'Эрчимжүүлсэн 6 сарын хөтөлбөр — өдрийн цагаар системтэй суралцана.',
  },
  {
    id: 'intensive1',
    level: 'Эрчимжүүлсэн',
    hsk: '1 сар',
    title: 'Эрчимжүүлсэн 1 сарын анги',
    subtitle: 'Богино хугацаанд хурдацтай',
    duration: '1 сар',
    mode: 'Эрчимжүүлсэн',
    schedule: 'Өдөр / Орой',
    priceLabel: 'Зөвлөгөө аваарай',
    seatsLeft: 9,
    points: ['Богино эрчимтэй', 'Түвшин тогтоох', 'Шуурхай үр дүн'],
    badge: null,
    description: '1 сарын эрчимжүүлсэн анги — хурдацтай ахиц гаргана.',
  },
  {
    id: 'regular1',
    level: 'Энгийн',
    hsk: '1 сар',
    title: 'Энгийн 1 сарын анги',
    subtitle: 'Ажлын дараа суралцах',
    duration: '1 сар',
    mode: 'Оройн анги',
    schedule: 'Оройн цаг',
    priceLabel: 'Зөвлөгөө аваарай',
    seatsLeft: 14,
    points: ['Уян хатан хуваарь', 'Жижиг бүлэг', 'Практик яриа'],
    badge: null,
    description: 'Ажилтай хүмүүст тохирсон энгийн 1 сарын анги.',
  },
  {
    id: 'private',
    level: 'Ганцаарчилсан',
    hsk: '1:1',
    title: 'Ганцаарчилсан хичээл',
    subtitle: '7 хоногийн хувийн хөтөлбөр',
    duration: '7 хоног+',
    mode: '1:1',
    schedule: 'Тохиролцоогоор',
    priceLabel: 'Зөвлөгөө аваарай',
    seatsLeft: 6,
    points: ['Хувийн төлөвлөгөө', 'Уян цаг', 'Шууд засвар'],
    badge: 'Зөвлөмж',
    description: 'Ганцаарчилсан хичээл — таны түвшинд тохируулсан.',
  },
]

export const courses = coursesFallback.map((c) => ({
  ...c,
  price: c.priceLabel,
}))

export const universities = [
  {
    id: 'blcu',
    name: 'Beijing Language and Culture University',
    nameMn: 'Бээжингийн хэл, соёлын их сургууль',
    short: 'BLCU',
    city: 'Бээжин',
    focus: 'Хэлний суурь бэлтгэл',
    intake: 'Хавар / Намар',
    hsk: 'HSK 3+',
    duration: '1–2 жил',
    tuition: '¥18,000–26,000 / жил',
    badge: 'Зөвлөмж',
    featured: true,
    image:
      'https://picsum.photos/seed/campus-blcu/1200/750',
    description:
      'Хятад хэл сурахад хамгийн тохиромжтой их сургууль. Гадаад оюутны хэлний бэлтгэлээрээ алдартай.',
    points: [
      'Хэлний суурь бэлтгэлийн хүчтэй хөтөлбөр',
      'Гадаад оюутны томоохон орчин',
      'HSK бэлтгэлтэй ойр холбоо',
    ],
    requirements: ['Паспорт', 'Диплом / гэрчилгээ', 'HSK 3 ба түүнээс дээш', 'Эрүүл мэндийн үзлэг'],
    why: 'Хятад хэлээ эхнээс нь эсвэл дунд түвшинд системтэй сурах хүсвэл эхний сонголт.',
  },
  {
    id: 'thu',
    name: 'Tsinghua University',
    nameMn: 'Цинхуа их сургууль',
    short: 'THU',
    city: 'Бээжин',
    focus: 'Инженер, бизнес',
    intake: 'Намар',
    hsk: 'HSK 5–6',
    duration: '4 жил · магистр 2–3',
    tuition: '¥26,000–40,000 / жил',
    badge: 'Тэргүүлэх',
    featured: true,
    image:
      'https://picsum.photos/seed/campus-thu/1200/750',
    description:
      'Хятадын тэргүүлэх их сургуулиудын нэг. Инженер, технологи, бизнесийн чиглэлээр хүчтэй.',
    points: [
      'Дэлхийн түвшний судалгаа',
      'Инженер · IT · бизнес',
      'Өндөр өрсөлдөөнтэй элсэлт',
    ],
    requirements: ['Паспорт', 'Диплом + дүн', 'HSK 5–6 эсвэл англи хэлний шалгалт', 'Зөвлөмжийн захидал'],
    why: 'Инженер, технологи, бизнесийн чиглэлээр дээд түвшинд суралцах хүсэлтэй бол.',
  },
  {
    id: 'pku',
    name: 'Peking University',
    nameMn: 'Бээжингийн их сургууль',
    short: 'PKU',
    city: 'Бээжин',
    focus: 'Нийгэм, хэл шинжлэл',
    intake: 'Намар',
    hsk: 'HSK 5–6',
    duration: '4 жил · магистр 2–3',
    tuition: '¥26,000–40,000 / жил',
    badge: 'Тэргүүлэх',
    featured: true,
    image:
      'https://picsum.photos/seed/campus-pku/1200/750',
    description:
      'Хятадын хамгийн нэр хүндтэй их сургуулиудын нэг. Нийгмийн ухаан, хэл шинжлэл, хууль зүйгээрээ алдартай.',
    points: [
      'Академийн өндөр нэр хүнд',
      'Өргөн хүрээний мэргэжил',
      'Бээжингийн төв орчин',
    ],
    requirements: ['Паспорт', 'Диплом + дүн', 'HSK 5–6', 'Motivation letter'],
    why: 'Нийгмийн ухаан, хэл, хууль, эдийн засгийн чиглэлээр суралцах хүсвэл.',
  },
  {
    id: 'fudan',
    name: 'Fudan University',
    nameMn: 'Фудань их сургууль',
    short: 'Fudan',
    city: 'Шанхай',
    focus: 'Эдийн засаг, медиа',
    intake: 'Хавар / Намар',
    hsk: 'HSK 5+',
    duration: '4 жил',
    tuition: '¥23,000–35,000 / жил',
    badge: null,
    featured: true,
    image:
      'https://picsum.photos/seed/campus-fudan/1200/750',
    description:
      'Шанхайн нэр хүндтэй их сургууль. Эдийн засаг, олон улсын харилцаа, медиа чиглэлээр хүчтэй.',
    points: [
      'Шанхайн бизнесийн орчин',
      'Эдийн засаг · медиа',
      'Олон улсын хөтөлбөрүүд',
    ],
    requirements: ['Паспорт', 'Диплом', 'HSK 5+', 'Санхүүгийн баталгаа'],
    why: 'Шанхайд суралцаж, эдийн засаг · медиа чиглэлээр ахиц гаргахыг хүсвэл.',
  },
  {
    id: 'sjtu',
    name: 'Shanghai Jiao Tong University',
    nameMn: 'Шанхайн Жяотун их сургууль',
    short: 'SJTU',
    city: 'Шанхай',
    focus: 'Технологи, дизайн',
    intake: 'Намар',
    hsk: 'HSK 5+',
    duration: '4 жил',
    tuition: '¥24,000–38,000 / жил',
    badge: null,
    featured: false,
    image:
      'https://picsum.photos/seed/campus-sjtu/1200/750',
    description:
      'Технологи, инженер, дизайны чиглэлээрээ хүчтэй. Шанхайн үйлдвэрлэл, инновацитай ойр.',
    points: [
      'Технологи · инженер',
      'Инновацийн экосистем',
      'Олон улсын хамтын ажиллагаа',
    ],
    requirements: ['Паспорт', 'Диплом + дүн', 'HSK 5 эсвэл IELTS/TOEFL', 'Портфолио (зарим мэргэжил)'],
    why: 'Технологи, дизайн, инженерийн чиглэлээр Шанхайд суралцах хүсвэл.',
  },
  {
    id: 'zju',
    name: 'Zhejiang University',
    nameMn: 'Жэжян их сургууль',
    short: 'ZJU',
    city: 'Ханжоу',
    focus: 'Мэдээллийн технологи',
    intake: 'Намар',
    hsk: 'HSK 5+',
    duration: '4 жил',
    tuition: '¥20,000–32,000 / жил',
    badge: 'IT',
    featured: true,
    image:
      'https://picsum.photos/seed/campus-zju/1200/750',
    description:
      'Ханжоу хотын тэргүүлэх их сургууль. IT, AI, инновацийн чиглэлээрээ хүчтэй — Alibaba-ийн төвтэй ойр.',
    points: [
      'IT · AI орчин',
      'Ханжоугийн технологийн экосистем',
      'Судалгааны хүчтэй бааз',
    ],
    requirements: ['Паспорт', 'Диплом', 'HSK 5+', 'Элсэлтийн ярилцлага (зарим хөтөлбөр)'],
    why: 'IT, технологийн салбарт суралцаж, Ханжоугийн инновацийн орчинд орохыг хүсвэл.',
  },
  {
    id: 'nju',
    name: 'Nanjing University',
    nameMn: 'Нанжин их сургууль',
    short: 'NJU',
    city: 'Нанжин',
    focus: 'Шинжлэх ухаан, хэл',
    intake: 'Намар',
    hsk: 'HSK 5+',
    duration: '4 жил',
    tuition: '¥20,000–30,000 / жил',
    badge: null,
    featured: false,
    image:
      'https://picsum.photos/seed/campus-nju/1200/750',
    description:
      'Нанжингийн түүхэн их сургууль. Шинжлэх ухаан, хэл, түүхийн чиглэлээр хүчтэй.',
    points: ['Түүхэн кампус', 'Академийн өндөр түвшин', 'Хэл · шинжлэх ухаан'],
    requirements: ['Паспорт', 'Диплом', 'HSK 5+', 'Санхүүгийн баталгаа'],
    why: 'Түүх, хэл, шинжлэх ухааны чиглэлээр суралцах хүсвэл.',
  },
  {
    id: 'whu',
    name: 'Wuhan University',
    nameMn: 'Ухань их сургууль',
    short: 'WHU',
    city: 'Ухань',
    focus: 'Хууль, эдийн засаг',
    intake: 'Намар',
    hsk: 'HSK 4+',
    duration: '4 жил',
    tuition: '¥18,000–28,000 / жил',
    badge: 'Гоё кампус',
    featured: false,
    image:
      'https://picsum.photos/seed/campus-whu/1200/750',
    description:
      'Уханьгийн алдартай их сургууль. Гоё кампус, хууль, эдийн засгийн хөтөлбөрөөрөө танигдсан.',
    points: ['Гоё кампус орчин', 'Хууль · эдийн засаг', 'Хувьцааны зардал бага'],
    requirements: ['Паспорт', 'Диплом', 'HSK 4–5', 'Эрүүл мэндийн үзлэг'],
    why: 'Зардал бага, кампус сайтай орчинд суралцахыг хүсвэл.',
  },
  {
    id: 'sysu',
    name: 'Sun Yat-sen University',
    nameMn: 'Сун Ят-сен их сургууль',
    short: 'SYSU',
    city: 'Гуанжоу',
    focus: 'Бизнес, анагаах',
    intake: 'Намар',
    hsk: 'HSK 5+',
    duration: '4–5 жил',
    tuition: '¥22,000–36,000 / жил',
    badge: null,
    featured: false,
    image:
      'https://picsum.photos/seed/campus-sysu/1200/750',
    description:
      'Өмнөд Хятадын тэргүүлэх их сургууль. Бизнес, анагаах ухаан, олон улсын хөтөлбөрүүдтэй.',
    points: ['Гуанжоугийн бизнес орчин', 'Анагаах · бизнес', 'Олон улсын холбоо'],
    requirements: ['Паспорт', 'Диплом + дүн', 'HSK 5+', 'Motivation letter'],
    why: 'Өмнөд Хятад, бизнес эсвэл анагаах чиглэлээр суралцах хүсвэл.',
  },
  {
    id: 'ruc',
    name: 'Renmin University of China',
    nameMn: 'Хятадын Ардын их сургууль',
    short: 'RUC',
    city: 'Бээжин',
    focus: 'Нийгэм, хууль, эдийн засаг',
    intake: 'Намар',
    hsk: 'HSK 5+',
    duration: '4 жил',
    tuition: '¥24,000–34,000 / жил',
    badge: null,
    featured: false,
    image:
      'https://picsum.photos/seed/campus-ruc/1200/750',
    description:
      'Нийгмийн ухаан, хууль, эдийн засгийн чиглэлээрээ Хятадад тэргүүлдэг.',
    points: ['Нийгмийн ухааны хүч', 'Бээжингийн төв', 'Төрийн бодлоготой ойр'],
    requirements: ['Паспорт', 'Диплом', 'HSK 5–6', 'Зөвлөмжийн захидал'],
    why: 'Нийгэм, хууль, эдийн засгийн гүнзгийрүүлсэн сургалт хүсвэл.',
  },
  {
    id: 'tongji',
    name: 'Tongji University',
    nameMn: 'Тунжи их сургууль',
    short: 'Tongji',
    city: 'Шанхай',
    focus: 'Архитектур, инженер',
    intake: 'Намар',
    hsk: 'HSK 5+',
    duration: '4–5 жил',
    tuition: '¥24,000–38,000 / жил',
    badge: 'Архитектур',
    featured: false,
    image:
      'https://picsum.photos/seed/campus-tongji/1200/750',
    description:
      'Архитектур, хот төлөвлөлт, инженерийн чиглэлээрээ алдартай Шанхайн их сургууль.',
    points: ['Архитектурын нэр хүнд', 'Инженер · дизайн', 'Германы хамтын ажиллагаа'],
    requirements: ['Паспорт', 'Диплом', 'HSK 5 эсвэл англи', 'Портфолио (архитектур)'],
    why: 'Архитектур, хот төлөвлөлт, инженерийн чиглэлээр суралцах хүсвэл.',
  },
  {
    id: 'buaa',
    name: 'Beihang University',
    nameMn: 'Бэйхан их сургууль',
    short: 'BUAA',
    city: 'Бээжин',
    focus: 'Нисэх, сансар, IT',
    intake: 'Намар',
    hsk: 'HSK 5+',
    duration: '4 жил',
    tuition: '¥25,000–38,000 / жил',
    badge: null,
    featured: false,
    image:
      'https://picsum.photos/seed/campus-buaa/1200/750',
    description:
      'Нисэх, сансрын технологи, IT-ийн чиглэлээрээ хүчтэй. Бээжингийн шилдэг техникийн их сургууль.',
    points: ['Аэрокосмос', 'IT · инженер', 'Судалгааны хүчтэй бааз'],
    requirements: ['Паспорт', 'Диплом + дүн', 'HSK 5+', 'Математикын суурь'],
    why: 'Нисэх, сансар, IT инженерийн чиглэлээр суралцах хүсвэл.',
  },
]

export const videos = [
  {
    id: 'r1',
    reelId: '990999057278500',
    title: 'ХАНЗ хичээлийн reel',
    category: 'Reel',
    views: '135K',
    thumb: '/cover.jpg',
  },
  {
    id: 'r2',
    reelId: '2238993540212913',
    title: 'Хятад хэлний богино хичээл',
    category: 'Reel',
    views: '46K',
    thumb: '/reels/r2.jpg',
  },
  {
    id: 'r3',
    reelId: '1024668917054226',
    title: 'HSK зөвлөмж · богино бичлэг',
    category: 'HSK',
    views: '24K',
    thumb: '/cover.jpg',
  },
  {
    id: 'r4',
    reelId: '1580290170446592',
    title: 'Ханз Академи · хичээлийн агшин',
    category: 'Академи',
    views: '21K',
    thumb: '/reels/r4.jpg',
  },
  {
    id: 'r5',
    reelId: '2101596603774278',
    title: 'Яриа / дуудлагын дасгал',
    category: 'Яриа',
    views: '15K',
    thumb: '/cover.jpg',
  },
  {
    id: 'r6',
    reelId: '1957662221536738',
    title: 'Шинэ хичээлийн мэдээ',
    category: 'Мэдээ',
    views: '8.2K',
    thumb: '/reels/r6.jpg',
  },
  {
    id: 'r7',
    reelId: '4645301932358133',
    title: 'ХАНЗ богино хичээл',
    category: 'Reel',
    views: '6.3K',
    thumb: '/cover.jpg',
  },
  {
    id: 'r8',
    reelId: '1065155426143855',
    title: 'Элсэлт · сургалтын мэдээлэл',
    category: 'Элсэлт',
    views: '4.6K',
    thumb: '/cover.jpg',
  },
]

export const products = [
  {
    id: 'p1',
    name: 'HSK 3 Standard Course',
    price: '₮89,000',
    tag: 'Ном',
    blurb: 'Албан ёсны сурах бичиг',
    description: 'HSK 3 албан ёсны сурах бичиг — дасгал, жишээтэй.',
    points: ['Албан ёсны материал', 'Дасгалтай', 'Шалгалтад тохирсон'],
  },
  {
    id: 'p2',
    name: 'HSK 4 үгийн багц',
    price: '₮45,000',
    tag: 'Карт',
    blurb: '1200 үгийн флашкарт',
    description: 'HSK 4 түвшний үгсийн флашкарт багц.',
    points: ['1200 үг', 'Зөөврийн', 'Давтах амар'],
  },
  {
    id: 'p3',
    name: 'ХАНЗ Hoodie',
    price: '₮129,000',
    tag: 'Merch',
    blurb: 'Брэндийн хувцас',
    description: 'ХАНЗ брэндийн hoodie — өдөр тутмын хэрэглээнд.',
    points: ['Чанартай даавуу', 'Тав тухтай', 'Брэндийн дизайн'],
  },
  {
    id: 'p4',
    name: 'Бичгийн дэвтэр',
    price: '₮28,000',
    tag: 'Дэвтэр',
    blurb: 'Иероглиф бичих тор',
    description: 'Иероглиф бичих дадлын дэвтэр.',
    points: ['Тортой хуудас', 'Практик', 'Эхлэгчдэд тохиромжтой'],
  },
  {
    id: 'p5',
    name: 'HSK Mock Test',
    price: '₮65,000',
    tag: 'Шалгалт',
    blurb: '3 бүрэн mock тест',
    description: '3 бүрэн mock шалгалтын багц.',
    points: ['3 тест', 'Хариулттай', 'Цаг хэмжих'],
  },
  {
    id: 'p6',
    name: 'ХАНЗ цүнх',
    price: '₮49,000',
    tag: 'Merch',
    blurb: 'Canvas tote',
    description: 'ХАНЗ canvas tote цүнх.',
    points: ['Бараатай', 'Хөнгөн', 'Өдөр тутмын'],
  },
]
